### ISSUE TITLE
Game isn't really a game

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [EclipseLikesSpace/The-Rules-For-Rulers#8]
Game isn't in a playable state, in fact when you go to the `game.html` in `/build`, all there is, is the tagline of the game and 3 paragraphs with Lorem Ipsum in each

**Comment by Just-a-Unity-Dev** [comment]
Working on issue, requesting more contributors

**Comment by vi241** [comment]
well... its dead now

**Comment by Just-a-Unity-Dev** [comment]
true...
